/*
-- Creando el Esquema de : 'CafeteriaMexicana'
--UNAM - IIMAS
--Maestría en Ciencias e Ingeniería en Computación
--
*/
CREATE DATABASE IF NOT EXISTS CafeteriaMexicana;
USE CafeteriaMexicana;



--
-- DEFINITION OF TABLE USUARIOS
--

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS 
(
  ID_USUARIO INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO varchar(30) NOT NULL  ,
  NOMBRE VARCHAR(90)   NOT NULL ,
  APELLIDO_PATERNO VARCHAR(50)    ,
  APELLIDO_MATERNO VARCHAR(50)    ,
  PASSWORD varchar(18) NOT NULL,
  TIPO_USUARIO varchar(100) NOT NULL,
  FECHA_ALTA timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,   
  PRIMARY KEY  (ID_USUARIO)
)
 ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=latin1;





--
-- DEFINITION OF TABLE PRODUCTOS
--

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS 
(
  ID_PRODUCTO INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE_PRODUCTO VARCHAR(100) NOT NULL  ,
  CANTIDAD_DISPONIBLE INT(10)   NOT NULL ,
  PRECIO_UNITARIO_PRODUCTO INT(10)    ,
  CADUCIDAD DATE NOT NULL    , 
  ESTATUS TINYINT(1) DEFAULT NULL, 
  PRIMARY KEY  (ID_PRODUCTO)
)
 ENGINE=INNODB AUTO_INCREMENT=61 DEFAULT CHARSET=LATIN1;



--
-- DEFINITION OF TABLE TICKETS
--

DROP TABLE IF EXISTS TICKETS;
CREATE TABLE TICKETS 
(
  ID_TICKET INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,   
  ID_USUARIO INT(10)  UNSIGNED  NOT NULL , 
  FECHA_TICKET DATE        ,  
  MONTO_TOTAL INT (10)  NOT NULL,  
  PRIMARY KEY  (ID_TICKET),  
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
) 
ENGINE=INNODB AUTO_INCREMENT=61 DEFAULT CHARSET=LATIN1;
 
 
 
--
-- DEFINITION OF TABLE VENTAS
--

DROP TABLE IF EXISTS VENTAS;
CREATE TABLE VENTAS 
(
  ID_TICKET INT(10) UNSIGNED NOT NULL ,
  ID_PRODUCTO INT(10) UNSIGNED NOT NULL  , 
  CANTIDAD_PRODUCTO_VENTA INT(10)  unsigned default NULL  ,
  MONTO_TOTAL_PRODUCTO INT(10) unsigned default NULL   , 
  PRIMARY KEY  (ID_TICKET,ID_PRODUCTO),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),  
  FOREIGN KEY (ID_TICKET) REFERENCES TICKETS (ID_TICKET)
) 
ENGINE=INNODB AUTO_INCREMENT=61 DEFAULT CHARSET=LATIN1;
 
 
 
 
 
/*!40000 ALTER TABLE USUARIOS DISABLE KEYS */;
INSERT INTO USUARIOS (ID_USUARIO,USUARIO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PASSWORD,TIPO_USUARIO,FECHA_ALTA) VALUES 
 (1,'ADMINISTRADOR','JOSEFA','DOMINGUEZ','REYES','admin123',1,'2019-05-30 12:02:26' ),
 (2,'VENDEDORA1','LUISA','ALVAREZ','GÓMEZ','ventas123',2,'2019-05-30 12:02:26' ) ;
  
 
  
 